w=float(input('enter ur weight in "Kgs"  '))
h=float(input('enter ur height in "m"  '))
print('your weight is : '+str(w)+'\tkgs')
print('your height is : '+str(h)+'\tm')
bmi=(w/h/h)
print('ur body mass index is: '+str(bmi)+'\tkg/m^2')