d=float(input(('enter distance  ')))
c=float(input(('enter cost of diesel  ')))
m=float(input(('enter mialege of your car  ')))
d=float(d+d)
tfc=float(d/m)
tc=float(tfc*c)
print('total fuel cost is: '+str(tc))